#!/bin/sh

##########  START OF SETTINGS  ##############

# Your search word may use regular expressions and end with an asterisk -
# e.g. term* will search for 'terminal', 'terminate' etc.
QUERY=your_search_word

DIR=directory_of_the_files_you_want_to_search

GREPIUSDIR=directory_of_this_script

##########  END OF SETTINGS  ###############

cd $GREPIUSDIR
grep -r --before-context=1 --after-context=1 --color=always $QUERY $DIR/*
